<?php

/**
 * @file
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_presave().
 */
function shentity_entity_presave(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'shentity') {
    $key = $entity->get('full_key')->value;
    $fields = $entity->get('field_row')->value;
    $type = $entity->get('type')->value;
    $sheet_number = $entity->get('sheet_number')->value;
    $shift = $entity->get('shift')->value;
    $google_sheet = \Drupal::service('shentity.pull.google.sheet');

    $google_sheet->fetch($key, $fields, $type, $sheet_number, $shift, TRUE);
    $sheet_data = $google_sheet->getData();
    if ($sheet_data instanceof \Stringable || $sheet_data instanceof \Drupal\Component\Render\MarkupInterface) {
      $sheet_data = (string) $sheet_data;
    }
    $entity->set('sheet', $sheet_data);
  }
}

/**
 * Implements hook_form_alter().
 */
function shentity_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'shentity_form') {
    // Old key field is hidden and not used anymore, but we want to keep it
    // in the database for now.
    if (isset($form['key'])) {
      $form['key']['#access'] = FALSE;
    }
    if (isset($form['sheet_number'])) {
      $form['sheet_number']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_cron().
 */
function shentity_cron() {
  $shentity_update = FALSE;
  $gss_node_update = FALSE;
  if (date('G', time()) > 03) {
    $shentity_update = TRUE;
  }
  if ((date('G', time()) == 04) && (date('i', time()) < 15)) {
    $gss_node_update = TRUE;
  }
  if ($shentity_update) {
    $date = new DrupalDateTime('-12 hours');
    $yesterday = $date->format('U');
    $query = \Drupal::entityQuery('shentity');
    $query->condition('changed', $yesterday, '<=');
    $query->accessCheck(FALSE);
    $results = $query->execute();
    $i = 0;
    foreach ($results as $sid) {
      if ($i < 5) {
        $now = new DrupalDateTime();
        $entity = \Drupal::entityTypeManager()->getStorage('shentity')->load($sid);
        $entity->set('sheet', '');
        $entity->setChangedTime($now->format('U'));
        $entity->save();
      }
      $i++;
    }
  }
  if ($gss_node_update) {
    $search_gss = \Drupal::entityQuery('node');
    $search_gss->condition('body', '[/gss]', 'CONTAINS');
    $search_gss->condition('changed', $yesterday, '<=');
    $search_gss->accessCheck(FALSE);
    $search_gss_results = $search_gss->execute();
    foreach ($search_gss_results as $gss_node) {
      $node_loaded = \Drupal::entityTypeManager()->getStorage('node')->load($gss_node);
      Cache::invalidateTags($node_loaded->getCacheTags());
    }
  }
}
